In [1]:
# Import required libraries and dependencies
import pandas as pd
import hvplot.pandas
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [2]:
# Load the data into a Pandas DataFrame
df_market_data = pd.read_csv(
    "Resources/crypto_market_data.csv",
    index_col="coin_id")

# Display sample data
df_market_data.head(10)

,price_change_percentage_24h,price_change_percentage_7d,price_change_percentage_14d,price_change_percentage_30d,price_change_percentage_60d,price_change_percentage_200d,price_change_percentage_1y
coin_id,,,,,,,
bitcoin,1.08388,7.60278,6.57509,7.67258,-3.25185,83.51840,37.51761
ethereum,0.22392,10.38134,4.80849,0.13169,-12.88890,186.77418,101.96023
tether,-0.21173,0.04935,0.00640,-0.04237,0.28037,-0.00542,0.01954
ripple,-0.37819,-0.60926,2.24984,0.23455,-17.55245,39.53888,-16.60193
bitcoin-cash,2.90585,17.09717,14.75334,15.74903,-13.71793,21.66042,14.49384
binancecoin,2.10423,12.85511,6.80688,0.05865,36.33486,155.61937,69.69195
chainlink,-0.23935,20.69459,9.30098,-11.21747,-43.69522,403.22917,325.13186
cardano,0.00322,13.99302,5.55476,10.10553,-22.84776,264.51418,156.09756
litecoin,-0.06341,6.60221,7.28931,1.21662,-17.23960,27.49919,-12.66408
bitcoin-cash-sv,0.92530,3.29641,-1.86656,2.88926,-24.87434,7.42562,93.73082

In [3]:
# Generate summary statistics
df_market_data.describe()

,price_change_percentage_24h,price_change_percentage_7d,price_change_percentage_14d,price_change_percentage_30d,price_change_percentage_60d,price_change_percentage_200d,price_change_percentage_1y
count,41.000000,41.000000,41.000000,41.000000,41.000000,41.000000,41.000000
mean,-0.269686,4.497147,0.185787,1.545693,-0.094119,236.537432,347.667956
std,2.694793,6.375218,8.376939,26.344218,47.365803,435.225304,1247.842884
min,-13.527860,-6.094560,-18.158900,-34.705480,-44.822480,-0.392100,-17.567530
25%,-0.608970,0.047260,-5.026620,-10.438470,-25.907990,21.660420,0.406170
50%,-0.063410,3.296410,0.109740,-0.042370,-7.544550,83.905200,69.691950
75%,0.612090,7.602780,5.510740,4.578130,0.657260,216.177610,168.372510
max,4.840330,20.694590,24.239190,140.795700,223.064370,2227.927820,7852.089700

In [6]:
# Plot your data to see what's in your DataFrame
df_market_data.hvplot.line(
    width=800,
    height=400,
    rot=90
)

:NdOverlay   [Variable]
   :Curve   [coin_id]   (value)

---

### Prepare the Data

In [7]:
# Use the `StandardScaler()` module from scikit-learn to normalize the data from the CSV file
scaled_data = StandardScaler().fit_transform(df_market_data)

In [8]:
# Create a DataFrame with the scaled data
scaled_df = pd.DataFrame(scaled_data, columns=['price_change_percentage_24h','price_change_percentage_7d','price_change_percentage_14d','price_change_percentage_30d','price_change_percentage_60d','price_change_percentage_200d','price_change_percentage_1y'])

# Copy the crypto names from the original DataFrame
scaled_df['coin_id'] = df_market_data.index

# Set the coin_id column as index
scaled_df.set_index('coin_id', inplace=True)

# Display the scaled DataFrame
scaled_df

,price_change_percentage_24h,price_change_percentage_7d,price_change_percentage_14d,price_change_percentage_30d,price_change_percentage_60d,price_change_percentage_200d,price_change_percentage_1y
coin_id,,,,,,,
bitcoin,0.508529,0.493193,0.772200,0.235460,-0.067495,-0.355953,-0.251637
ethereum,0.185446,0.934445,0.558692,-0.054341,-0.273483,-0.115759,-0.199352
tether,0.021774,-0.706337,-0.021680,-0.061030,0.008005,-0.550247,-0.282061
ripple,-0.040764,-0.810928,0.249458,-0.050388,-0.373164,-0.458259,-0.295546
bitcoin-cash,1.193036,2.000959,1.760610,0.545842,-0.291203,-0.499848,-0.270317
binancecoin,0.891871,1.327295,0.800214,-0.057148,0.778653,-0.188232,-0.225533
chainlink,0.011397,2.572251,1.101647,-0.490495,-0.931954,0.387759,-0.018284
cardano,0.102530,1.508001,0.648885,0.328959,-0.486349,0.065080,-0.155428
litecoin,0.077497,0.334297,0.858520,-0.012646,-0.366477,-0.486266,-0.292351
bitcoin-cash-sv,0.448952,-0.190684,-0.248043,0.051634,-0.529666,-0.532961,-0.206029
crypto-com-chain,0.331280,-1.614844,-1.054521,-0.729931,-0.350155,-0.022866,-0.034570
usd-coin,0.034352,-0.733026,-0.023140,-0.065775,0.002925,-0.550599,-0.282232
eos,0.155710,-0.922491,0.115024,-0.237488,-0.642837,-0.508220,-0.296330
monero,0.262723,1.792602,2.202665,1.437842,0.893865,-0.155893,-0.167644
tron,0.130050,-0.041018,0.147155,-0.543776,0.120116,-0.241118,-0.234014
tezos,-0.151583,0.708196,0.258012,-0.602296,-0.956049,-0.449211,-0.168479
okb,-0.923203,-1.437359,-0.629963,-0.460558,-0.058504,-0.457283,-0.166900
stellar,-0.277543,-0.385209,-0.153243,-0.371816,-0.656403,-0.353387,-0.270874
cosmos,-0.255978,1.840274,0.643565,0.116538,-0.151913,-0.117565,-0.215191
cdai,0.180851,-0.704931,-0.001816,-0.143237,0.016060,-0.551146,-0.282310
neo,0.286546,-0.326301,-1.212670,-0.903134,0.290970,-0.181187,-0.175550
wrapped-bitcoin,0.515453,0.461843,0.769975,0.224045,-0.074674,-0.355054,-0.251623
leo-token,0.051758,-0.928381,-0.871918,0.058782,-0.159250,-0.512071,-0.265036
huobi-token,-0.052032,-0.457229,0.032522,-0.184489,-0.070809,-0.451982,-0.262140
nem,-0.217984,-0.849381,0.297632,-0.199820,1.773127,-0.047361,-0.119226
binance-usd,0.061339,-0.706669,-0.015321,-0.058694,0.004017,-0.550003,-0.281963
iota,0.259097,0.249508,-0.478953,-0.218997,-0.735815,-0.329179,-0.285310
vechain,0.585089,-0.994231,-2.217108,-0.603898,-0.930423,0.077149,-0.117482
zcash,-0.127467,0.929119,0.677532,0.223834,-0.437068,-0.265163,-0.214829
theta-token,-1.612188,-1.682027,-0.816921,1.148607,1.712641,1.502992,0.286977
dash,-0.296940,0.094763,0.040040,-0.358830,-0.558527,-0.535732,-0.284071
ethereum-classic,-0.071312,-0.229484,-0.175544,0.051882,-0.551760,-0.526060,-0.273062
ethlend,-4.981042,-0.045178,-1.206956,-1.212126,0.047736,4.632380,6.088625
maker,-0.125168,0.580730,-0.202356,0.582911,-0.395923,-0.358240,-0.273433
havven,-1.428574,-0.025510,-1.628859,-0.860354,-0.840714,0.898815,0.268647
omisego,1.919812,0.370447,-1.619761,-0.409716,1.696480,0.811207,-0.021888
celsius-degree-token,1.045530,-0.618328,2.907054,5.351455,4.769913,3.148875,1.348488
ontology,-0.409044,-0.906963,-1.298986,-1.393153,-0.696937,-0.422835,-0.292344
ftx-token,0.414711,0.414044,-0.047386,-0.465380,0.128185,-0.416502,-0.145469
true-usd,0.078038,-0.687745,-0.009191,-0.058214,0.007388,-0.550441,-0.281747
digibyte,1.217453,-0.607714,-0.907066,0.449939,-0.662530,0.572367,-0.132482

---

### Find the Best Value for k Using the Original Scaled DataFrame.

In [9]:
# Create a list with the number of k-values from 1 to 11
k = list(range(1,11))

In [14]:
# Create an empty list to store the inertia values
inertia = []

# Create a for loop to compute the inertia with each possible value of k
# Inside the loop:
# 1. Create a KMeans model using the loop counter for the n_clusters
# 2. Fit the model to the data using `df_market_data_scaled`
# 3. Append the model.inertia_ to the inertia list
for i in k:
    model = KMeans(n_clusters=i, random_state=1)
    model.fit(scaled_df)
    inertia.append(model.inertia_)

In [15]:
# Create a dictionary with the data to plot the Elbow curve
data = {'k':k,'inertia':inertia}

# Create a DataFrame with the data to plot the Elbow curve
df = pd.DataFrame(data)
df

    k     inertia
0   1  287.000000
1   2  212.123342
2   3  165.136752
3   4   79.022435
4   5   66.413051
5   6   61.634088
6   7   46.074467
7   8   43.392694
8   9   32.913223
9  10   30.469111

In [65]:
# Plot a line chart with all the inertia values computed with
# the different values of k to visually identify the optimal value for k.
line1 = df.hvplot.line(
    x='k',
    y='inertia',
    xticks=k,
    title='Non-PCA K values'
)
line1

:Curve   [k]   (inertia)

#### Answer the following question: 

**Question:** What is the best value for `k`?

**Answer:** From the graph here, it looks like `k=4` is the best value for `k`

---

### Cluster Cryptocurrencies with K-means Using the Original Scaled DataFrame

In [17]:
# Initialize the K-Means model using the best value for k
model = KMeans(n_clusters=4)

In [18]:
# Fit the K-Means model using the scaled DataFrame
model.fit(scaled_df)

KMeans(n_clusters=4)

In [19]:
# Predict the clusters to group the cryptocurrencies using the scaled DataFrame
predictions = model.predict(scaled_df)

# Print the resulting array of cluster values.
print(predictions)

[1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 0 1 0 1 1 2 1 0 0 3
 0 1 1 0]

In [20]:
# Create a copy of the scaled DataFrame
scaled_df_copy = scaled_df.copy()

In [22]:
# Add a new column to the copy of the scaled DataFrame with the predicted clusters
scaled_df_copy['cluster'] = predictions

# Display the copy of the scaled DataFrame
scaled_df_copy

,price_change_percentage_24h,price_change_percentage_7d,price_change_percentage_14d,price_change_percentage_30d,price_change_percentage_60d,price_change_percentage_200d,price_change_percentage_1y,cluster
coin_id,,,,,,,,
bitcoin,0.508529,0.493193,0.772200,0.235460,-0.067495,-0.355953,-0.251637,1
ethereum,0.185446,0.934445,0.558692,-0.054341,-0.273483,-0.115759,-0.199352,1
tether,0.021774,-0.706337,-0.021680,-0.061030,0.008005,-0.550247,-0.282061,1
ripple,-0.040764,-0.810928,0.249458,-0.050388,-0.373164,-0.458259,-0.295546,1
bitcoin-cash,1.193036,2.000959,1.760610,0.545842,-0.291203,-0.499848,-0.270317,1
binancecoin,0.891871,1.327295,0.800214,-0.057148,0.778653,-0.188232,-0.225533,1
chainlink,0.011397,2.572251,1.101647,-0.490495,-0.931954,0.387759,-0.018284,1
cardano,0.102530,1.508001,0.648885,0.328959,-0.486349,0.065080,-0.155428,1
litecoin,0.077497,0.334297,0.858520,-0.012646,-0.366477,-0.486266,-0.292351,1
bitcoin-cash-sv,0.448952,-0.190684,-0.248043,0.051634,-0.529666,-0.532961,-0.206029,1
crypto-com-chain,0.331280,-1.614844,-1.054521,-0.729931,-0.350155,-0.022866,-0.034570,0
usd-coin,0.034352,-0.733026,-0.023140,-0.065775,0.002925,-0.550599,-0.282232,1
eos,0.155710,-0.922491,0.115024,-0.237488,-0.642837,-0.508220,-0.296330,1
monero,0.262723,1.792602,2.202665,1.437842,0.893865,-0.155893,-0.167644,1
tron,0.130050,-0.041018,0.147155,-0.543776,0.120116,-0.241118,-0.234014,1
tezos,-0.151583,0.708196,0.258012,-0.602296,-0.956049,-0.449211,-0.168479,1
okb,-0.923203,-1.437359,-0.629963,-0.460558,-0.058504,-0.457283,-0.166900,0
stellar,-0.277543,-0.385209,-0.153243,-0.371816,-0.656403,-0.353387,-0.270874,1
cosmos,-0.255978,1.840274,0.643565,0.116538,-0.151913,-0.117565,-0.215191,1
cdai,0.180851,-0.704931,-0.001816,-0.143237,0.016060,-0.551146,-0.282310,1
neo,0.286546,-0.326301,-1.212670,-0.903134,0.290970,-0.181187,-0.175550,0
wrapped-bitcoin,0.515453,0.461843,0.769975,0.224045,-0.074674,-0.355054,-0.251623,1
leo-token,0.051758,-0.928381,-0.871918,0.058782,-0.159250,-0.512071,-0.265036,0
huobi-token,-0.052032,-0.457229,0.032522,-0.184489,-0.070809,-0.451982,-0.262140,1
nem,-0.217984,-0.849381,0.297632,-0.199820,1.773127,-0.047361,-0.119226,1
binance-usd,0.061339,-0.706669,-0.015321,-0.058694,0.004017,-0.550003,-0.281963,1
iota,0.259097,0.249508,-0.478953,-0.218997,-0.735815,-0.329179,-0.285310,1
vechain,0.585089,-0.994231,-2.217108,-0.603898,-0.930423,0.077149,-0.117482,0
zcash,-0.127467,0.929119,0.677532,0.223834,-0.437068,-0.265163,-0.214829,1
theta-token,-1.612188,-1.682027,-0.816921,1.148607,1.712641,1.502992,0.286977,0
dash,-0.296940,0.094763,0.040040,-0.358830,-0.558527,-0.535732,-0.284071,1
ethereum-classic,-0.071312,-0.229484,-0.175544,0.051882,-0.551760,-0.526060,-0.273062,1
ethlend,-4.981042,-0.045178,-1.206956,-1.212126,0.047736,4.632380,6.088625,2
maker,-0.125168,0.580730,-0.202356,0.582911,-0.395923,-0.358240,-0.273433,1
havven,-1.428574,-0.025510,-1.628859,-0.860354,-0.840714,0.898815,0.268647,0
omisego,1.919812,0.370447,-1.619761,-0.409716,1.696480,0.811207,-0.021888,0
celsius-degree-token,1.045530,-0.618328,2.907054,5.351455,4.769913,3.148875,1.348488,3
ontology,-0.409044,-0.906963,-1.298986,-1.393153,-0.696937,-0.422835,-0.292344,0
ftx-token,0.414711,0.414044,-0.047386,-0.465380,0.128185,-0.416502,-0.145469,1
true-usd,0.078038,-0.687745,-0.009191,-0.058214,0.007388,-0.550441,-0.281747,1
digibyte,1.217453,-0.607714,-0.907066,0.449939,-0.662530,0.572367,-0.132482,0

In [66]:
# Create a scatter plot using hvPlot by setting
# `x="price_change_percentage_24h"` and `y="price_change_percentage_7d"`.
# Color the graph points with the labels found using K-Means and
# add the crypto name in the `hover_cols` parameter to identify
# the cryptocurrency represented by each data point.
chart1 = scaled_df_copy.hvplot.scatter(
    x="price_change_percentage_24h",
    y="price_change_percentage_7d",
    by='cluster',
    hover_cols='coin_id',
    ylim = (-5,8),
    xlim = (-5.5,8.5),
    title='Clusters for Non-PCA data'
)
chart1

:NdOverlay   [cluster]
   :Scatter   [price_change_percentage_24h]   (price_change_percentage_7d,coin_id)

---

### Optimize Clusters with Principal Component Analysis.

In [25]:
# Create a PCA model instance and set `n_components=3`.
pca = PCA(n_components=3)

In [26]:
# Use the PCA model with `fit_transform` to reduce the original scaled DataFrame
# down to three principal components.
pca_data = pca.fit_transform(scaled_df)

# View the scaled PCA data
pca_data

array([[-0.60066733,  0.84276006,  0.46159457],
       [-0.45826071,  0.45846566,  0.95287678],
       [-0.43306981, -0.16812638, -0.64175193],
       [-0.47183495, -0.22266008, -0.47905316],
       [-1.15779997,  2.04120919,  1.85971527],
       [-0.51653377,  1.38837748,  0.80407131],
       [-0.45071134,  0.51769912,  2.84614316],
       [-0.34559977,  0.72943939,  1.47801284],
       [-0.64946792,  0.43216514,  0.60030286],
       [-0.75901394, -0.20119979, -0.21765292],
       [-0.24819846, -1.37625159, -1.46202571],
       [-0.43840762, -0.17533654, -0.6633884 ],
       [-0.69342533, -0.47381462, -0.52759693],
       [ 0.06049915,  2.90940385,  1.49857131],
       [-0.39335243, -0.10819197, -0.01275608],
       [-0.79617564, -0.49440875,  1.08281169],
       [ 0.06407452, -1.26982514, -1.09882928],
       [-0.48901506, -0.73271912, -0.06254323],
       [-0.3062723 ,  0.70341515,  1.71422359],
       [-0.51352775, -0.14280239, -0.65656583],
       [-0.36212044, -0.98691441, -0.72875232],
       [-0.60426463,  0.82739764,  0.43931594],
       [-0.4132956 , -0.67411527, -1.07662834],
       [-0.40748304, -0.21250655, -0.35142563],
       [ 0.60897382,  0.56353212, -1.14874159],
       [-0.45021114, -0.15101945, -0.64740061],
       [-0.76466522, -0.51788554,  0.20499029],
       [-0.55631468, -1.93820906, -1.26177589],
       [-0.42514677,  0.49297617,  1.05804837],
       [ 2.67686761, -0.0139541 , -1.96520722],
       [-0.61392275, -0.4793368 ,  0.33956513],
       [-0.57992398, -0.35633377, -0.11494202],
       [ 8.08901821, -3.89689054,  2.30138208],
       [-0.38904526,  0.16504063,  0.3794137 ],
       [ 0.86576183, -2.26188239,  0.27558289],
       [ 0.11167508,  0.42831576, -1.20539797],
       [ 4.7923954 ,  6.76767868, -1.98698545],
       [-0.63235492, -2.10811713, -0.65222738],
       [-0.59314216,  0.02148496,  0.20991142],
       [-0.4581305 , -0.13573403, -0.63528357],
       [-0.29791045, -0.1911256 , -0.90960173]])

In [28]:
# Retrieve the explained variance to determine how much information
# can be attributed to each principal component.
x = pca.explained_variance_ratio_
print(x)

[0.3719856  0.34700813 0.17603793]

In [29]:
total = 0
for num in x:
    total += num
print(total)

0.895031657030984

#### Answer the following question: 

**Question:** What is the total explained variance of the three principal components?

**Answer:** About 89.5%

In [39]:
# Create a new DataFrame with the PCA data.
pca_df = pd.DataFrame(pca_data, columns=['PC1','PC2','PC3'])

# Copy the crypto names from the original scaled DataFrame
pca_df['coin_id'] = df_market_data.index

# Set the coin_id column as index
pca_df.set_index('coin_id', inplace=True)

# Display the scaled PCA DataFrame
pca_df

                           PC1       PC2       PC3
coin_id
bitcoin              -0.600667  0.842760  0.461595
ethereum             -0.458261  0.458466  0.952877
tether               -0.433070 -0.168126 -0.641752
ripple               -0.471835 -0.222660 -0.479053
bitcoin-cash         -1.157800  2.041209  1.859715
binancecoin          -0.516534  1.388377  0.804071
chainlink            -0.450711  0.517699  2.846143
cardano              -0.345600  0.729439  1.478013
litecoin             -0.649468  0.432165  0.600303
bitcoin-cash-sv      -0.759014 -0.201200 -0.217653
crypto-com-chain     -0.248198 -1.376252 -1.462026
usd-coin             -0.438408 -0.175337 -0.663388
eos                  -0.693425 -0.473815 -0.527597
monero                0.060499  2.909404  1.498571
tron                 -0.393352 -0.108192 -0.012756
tezos                -0.796176 -0.494409  1.082812
okb                   0.064075 -1.269825 -1.098829
stellar              -0.489015 -0.732719 -0.062543
cosmos               -0.306272  0.703415  1.714224
cdai                 -0.513528 -0.142802 -0.656566
neo                  -0.362120 -0.986914 -0.728752
wrapped-bitcoin      -0.604265  0.827398  0.439316
leo-token            -0.413296 -0.674115 -1.076628
huobi-token          -0.407483 -0.212507 -0.351426
nem                   0.608974  0.563532 -1.148742
binance-usd          -0.450211 -0.151019 -0.647401
iota                 -0.764665 -0.517886  0.204990
vechain              -0.556315 -1.938209 -1.261776
zcash                -0.425147  0.492976  1.058048
theta-token           2.676868 -0.013954 -1.965207
dash                 -0.613923 -0.479337  0.339565
ethereum-classic     -0.579924 -0.356334 -0.114942
ethlend               8.089018 -3.896891  2.301382
maker                -0.389045  0.165041  0.379414
havven                0.865762 -2.261882  0.275583
omisego               0.111675  0.428316 -1.205398
celsius-degree-token  4.792395  6.767679 -1.986985
ontology             -0.632355 -2.108117 -0.652227
ftx-token            -0.593142  0.021485  0.209911
true-usd             -0.458131 -0.135734 -0.635284
digibyte             -0.297910 -0.191126 -0.909602

---

### Find the Best Value for k Using the Scaled PCA DataFrame

In [31]:
# Create a list with the number of k-values from 1 to 11
k = list(range(1,11))

In [32]:
# Create an empty list to store the inertia values
inertia = []

# Create a for loop to compute the inertia with each possible value of k
# Inside the loop:
# 1. Create a KMeans model using the loop counter for the n_clusters
# 2. Fit the model to the data using `df_market_data_pca`
# 3. Append the model.inertia_ to the inertia list
for i in k:
    model = KMeans(n_clusters=i, random_state=1)
    model.fit(pca_df)
    inertia.append(model.inertia_)

In [33]:
# Create a dictionary with the data to plot the Elbow curve
data = {'k':k,'inertia':inertia}
# Create a DataFrame with the data to plot the Elbow curve
df = pd.DataFrame(data)

In [63]:
# Plot a line chart with all the inertia values computed with
# the different values of k to visually identify the optimal value for k.
line2 = df.hvplot.line(
    x='k',
    y='inertia',
    xticks=k,
    title='K analysis for PCA'
)
line2

:Curve   [k]   (inertia)

#### Answer the following questions: 

* **Question:** What is the best value for `k` when using the PCA data?

  * **Answer:** it would appear `k=4` is still the optimal value


* **Question:** Does it differ from the best k value found using the original data?

  * **Answer:** no

### Cluster Cryptocurrencies with K-means Using the Scaled PCA DataFrame

In [40]:
# Initialize the K-Means model using the best value for k
model = KMeans(n_clusters=4, random_state=1)

In [41]:
# Fit the K-Means model using the PCA data
model.fit(pca_df)

KMeans(n_clusters=4, random_state=1)

In [42]:
# Predict the clusters to group the cryptocurrencies using the scaled PCA DataFrame
clusters = model.predict(pca_df)

# Print the resulting array of cluster values.
print(clusters)

[2 2 0 0 2 2 2 2 2 0 0 0 0 2 0 2 0 0 2 0 0 2 0 0 0 0 0 0 2 0 0 0 3 2 0 0 1
 0 0 0 0]

In [43]:
# Create a copy of the scaled PCA DataFrame
pca_df_copy = pca_df.copy()

# Add a new column to the copy of the PCA DataFrame with the predicted clusters
pca_df_copy['cluster'] = clusters

# Display the copy of the scaled PCA DataFrame
pca_df_copy

                           PC1       PC2       PC3  cluster
coin_id
bitcoin              -0.600667  0.842760  0.461595        2
ethereum             -0.458261  0.458466  0.952877        2
tether               -0.433070 -0.168126 -0.641752        0
ripple               -0.471835 -0.222660 -0.479053        0
bitcoin-cash         -1.157800  2.041209  1.859715        2
binancecoin          -0.516534  1.388377  0.804071        2
chainlink            -0.450711  0.517699  2.846143        2
cardano              -0.345600  0.729439  1.478013        2
litecoin             -0.649468  0.432165  0.600303        2
bitcoin-cash-sv      -0.759014 -0.201200 -0.217653        0
crypto-com-chain     -0.248198 -1.376252 -1.462026        0
usd-coin             -0.438408 -0.175337 -0.663388        0
eos                  -0.693425 -0.473815 -0.527597        0
monero                0.060499  2.909404  1.498571        2
tron                 -0.393352 -0.108192 -0.012756        0
tezos                -0.796176 -0.494409  1.082812        2
okb                   0.064075 -1.269825 -1.098829        0
stellar              -0.489015 -0.732719 -0.062543        0
cosmos               -0.306272  0.703415  1.714224        2
cdai                 -0.513528 -0.142802 -0.656566        0
neo                  -0.362120 -0.986914 -0.728752        0
wrapped-bitcoin      -0.604265  0.827398  0.439316        2
leo-token            -0.413296 -0.674115 -1.076628        0
huobi-token          -0.407483 -0.212507 -0.351426        0
nem                   0.608974  0.563532 -1.148742        0
binance-usd          -0.450211 -0.151019 -0.647401        0
iota                 -0.764665 -0.517886  0.204990        0
vechain              -0.556315 -1.938209 -1.261776        0
zcash                -0.425147  0.492976  1.058048        2
theta-token           2.676868 -0.013954 -1.965207        0
dash                 -0.613923 -0.479337  0.339565        0
ethereum-classic     -0.579924 -0.356334 -0.114942        0
ethlend               8.089018 -3.896891  2.301382        3
maker                -0.389045  0.165041  0.379414        2
havven                0.865762 -2.261882  0.275583        0
omisego               0.111675  0.428316 -1.205398        0
celsius-degree-token  4.792395  6.767679 -1.986985        1
ontology             -0.632355 -2.108117 -0.652227        0
ftx-token            -0.593142  0.021485  0.209911        0
true-usd             -0.458131 -0.135734 -0.635284        0
digibyte             -0.297910 -0.191126 -0.909602        0

In [67]:
# Create a scatter plot using hvPlot by setting
# `x="PC1"` and `y="PC2"`.
# Color the graph points with the labels found using K-Means and
# add the crypto name in the `hover_cols` parameter to identify
# the cryptocurrency represented by each data point.
chart2 = pca_df_copy.hvplot.scatter(
    x='PC1',
    y='PC2',
    by='cluster',
    ylim = (-5,8),
    xlim = (-5.5,8.5),
    title='Clusters for PCA'
)
chart2

:NdOverlay   [cluster]
   :Scatter   [PC1]   (PC2)

### Visualize and Compare the Results

In this section, you will visually analyze the cluster analysis results by contrasting the outcome with and without using the optimization techniques.

In [68]:
# Composite plot to contrast the Elbow curves
layout_plot = line1 + line2
layout_plot

:Layout
   .Curve.I  :Curve   [k]   (inertia)
   .Curve.II :Curve   [k]   (inertia)

In [69]:
# Composite plot to contrast the clusters
layout_plot = chart1 + chart2
layout_plot

:Layout
   .NdOverlay.I  :NdOverlay   [cluster]
      :Scatter   [price_change_percentage_24h]   (price_change_percentage_7d,coin_id)
   .NdOverlay.II :NdOverlay   [cluster]
      :Scatter   [PC1]   (PC2)

#### Answer the following question: 

  * **Question:** After visually analyzing the cluster analysis results, what is the impact of using fewer features to cluster the data using K-Means?

  * **Answer:** For the line charts, nothing really seems to change, which implies our data has retained its shape and should be good to use in either form. Moving then tot the scatter plots, it seems that rather than cluster the points tighter, the second run of the algorithm (PCA analysis) just sent the outliers off to the right. In this instance, the tigher cluster spread was shown WITHOUT doing the PCA analysis.